
name: ZAP-DAST

on:
  push:
    branches: [ "dast-pipeline" ]
  pull_request:
    branches: [ "dast-pipeline" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Spawn OWASP juice shop
        run: |
          docker run -d -p 3000:3000 bkimminich/juice-shop

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          artifact_name: 'DAST Report'
