name: "Semgrep SAST"

on:
  push:
    branches: [ "horusec" ]
  pull_request:
    branches: [ "horusec" ]

jobs:
  analyze:
    name: Analyze with Horusec
    runs-on: 'ubuntu-latest'
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: actions
          build-mode: none
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: juice-shop/juice-shop
    
    - name: Run horusec Scan
      run: | 
        docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src horuszup/horusec-cli:v2.9.0-beta.3 horusec start -p /src -P $(pwd) > results.tsv
    
    - name: Upload horusec Results
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-results
        path: ./results.tsv
