name: "semgrep scan"

on:
  push:
    branches: [ "semgrep" ]
  pull_request:
    branches: [ "semgrep" ]

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: 'ubuntu-latest'
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: actions
          build-mode: none
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install semgrep
      run: |
        sudo apt update && sudo apt install python3 pip
        python3 -m pip install semgrep
    
    - name: Run semgrep scan
      run: | 
        semgrep scan --config auto